[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.36"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.32.0"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"
