name: build-release

on:
  push:
    tags:
    - v*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17' # The Go version to download (if necessary) and use.
      - name: Test
        run: make test
      - name: Build
        run: |
          make linux arm macos
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        # softprops/action-gh-release v0.1.12
        uses: softprops/action-gh-release@2d72d869af3bf23602f9593a1e3fd739b80ac1eb
        with:
          files: |
            target/env-aws-params_linux-amd64
            target/env-aws-params_linux-arm64
            target/env-aws-params_darwin-amd64
          body: |
            See the [CHANGELOG](https://github.com/lnxjedi/env-aws-params/blob/main/CHANGELOG.md)
